backend:
  image: registry.relizahub.com/fe36fb39-6cf0-4ff6-8e19-a471628816b6-public/mafia-express@sha256:67d04c317dce2ab44db032fc52e876192a13c78de886bccfae700e5c36d70aee
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image:registry.relizahub.com/fe36fb39-6cf0-4ff6-8e19-a471628816b6-public/mafia-vue@sha256:cdfe4d45305c36b00550cd5884a1c28fe739b62dac0ce107d1b696aefc54aa2a
  replicaCount: 1
  port: 80
  targetPort: 80
redis:
  image: docker.io/library/redis:6.2.3-buster
ingress:
  minimalIngressEnabled: true
  nginxEnabled: false
  traefikEnabled: false
  host: localhost
